---
AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda for DynamoDB Create Table
Resources:
  MyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/lambda/lambda-dynamodb-read-item"
  IamRoleLambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: 'lambda-dynamodb-read-item-lambdaPolicy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            Resource:
            - Fn::Sub: arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/aws-sdk-iam-with-cf-cli:*
          - Effect: Allow
            Action:
            - logs:PutLogEvents
            Resource:
            - Fn::Sub: arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/aws-sdk-iam-with-cf-cli:*:*
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            Resource:
            - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*
      Path: "/"
      RoleName: 'lambda-dynamodb-read-item-lambdaRole'
  LambdaFunctionWithCF:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: 'serverless-cookbook'
        S3Key: lambda-dynamodb-read-item-0.0.1-SNAPSHOT.jar
      FunctionName: lambda-dynamodb-read-item
      Handler: tech.heartin.books.serverlesscookbook.MyLambdaHandler::handleRequest
      MemorySize: 512
      Role:
        Fn::GetAtt:
        - IamRoleLambdaExecution
        - Arn
      Runtime: java8
      Timeout: 15
    DependsOn:
    - MyLogGroup
    - IamRoleLambdaExecution
